# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.1 2003/04/03 23:44:03 reid Exp $
#
# (c) The GHC Team, 1999
#

TOP=../..
include $(TOP)/mk/boilerplate.mk

PACKAGE = xlib
IS_CBITS_LIB = YES
INSTALL_DATAS+=HsXlib.h

include $(TOP)/mk/target.mk
