#-----------------------------------------------------------------------------
# $Id: Makefile,v 1.1 2003/05/22 14:16:41 reid Exp $

TOP = ..
include $(TOP)/mk/boilerplate.mk

SGML_DOC = HSX11

include $(TOP)/mk/target.mk
