#-----------------------------------------------------------------------------
# $Id: Makefile,v 1.2 2004/03/07 01:04:24 ross Exp $

TOP = ../..
include $(TOP)/mk/boilerplate.mk

SGML_DOC = HSX11

include $(TOP)/mk/target.mk
